# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pratt SAVI 800
email:
description: > # this means to ignore newlines until "baseurl:"
  This website displays student projects from Pratt SAVI's SAVI-800,
  Advanced Interactive Web Mapping
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pratt-savi-800.github.io/" # the base hostname & protocol for your site
twitter_username: PrattSAVI
github_username: pratt-savi-800

# Build settings
markdown: kramdown
