# Site settings
title: Pratt SAVI 800
email:
description: > # this means to ignore newlines until "baseurl:"
  This website displays student projects from Pratt SAVI's SAVI-800,
  Advanced Interactive Web Mapping
baseurl: /
url: http://pratt-savi-800.github.io
twitter_username: PrattSAVI
github_username: pratt-savi-800

# Build settings
markdown: kramdown
